version: '3'

volumes:
  web_data: { }

services:

#  nginx:
#    container_name: gateway
#    image: gateway:latest
#    ports:
#      - '80:80'
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro

  webserver:
    build: .
    container_name: webserver
    image: webserver:latest
    ports:
      - 8080:8080
    volumes:
      - .:.
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/webdb
    links:
      - "pgsql:pgsql"
      - "redis:redis"
  #        restart: always

  pgsql:
    image: postgres:9.5
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=webdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - web_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
  #      restart: always

#  webclient:
#    container_name: webclient
#    image: webclient:latest
#    ports:
#      - 3000:3000

  redis:
    container_name: redis
    image: "redis:alpine"
    command: [ "redis-server" ]
    ports:
      - "6379:6379"

#    mongodb:
#        container_name: mongodb
#        image: mongo:latest
#        ports:
#          - 27017:27017
#        volumes:
#          - baseweb_data:/var/lib/mongodb/data