version: '3'

volumes:
  web_data: { }

services:

#  nginx:
#    container_name: gateway
#    image: gateway:latest
#    ports:
#      - '80:80'
#    volumes:
#      - /var/run/docker.sock:/tmp/docker.sock:ro

  web:
#    build: .
#    container_name: webserver
    image: web:latest
    volumes:
      - ./:/workspace/app
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://pgsql:5432/webdb
    restart: unless-stopped
    depends_on:
      - redis
      - pgsql
  #        restart: always

  pgsql:
    image: postgres:9.5
    container_name: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=webdb
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - .docker/data/db:/data/db
    ports:
      - 5432:5432
    restart: unless-stopped

#  webclient:
#    container_name: webclient
#    image: webclient:latest
#    ports:
#      - 3000:3000

  redis:
    container_name: redis
    image: "redis:alpine"
    volumes:
      - .docker/data/redis:/data
    command: [ "redis-server" ]
    ports:
      - "6379:6379"