version: '2.3'

volumes:
  baseweb_data: {}
  
services:
    
    nginx:
        container_name: gateway
        image: gateway:latest
        ports:
          - '80:80'
        volumes:
          - /var/run/docker.sock:/tmp/docker.sock:ro
    dms:
        container_name: dms 
        image: dms:latest
        expose:
        - "8080"
        environment:
          POSTGRES_DB: ${PG_DATABASE:-dms}
          POSTGRES_PASSWORD: ${PG_PASSWORD:-root}
          POSTGRES_USER: ${PG_USER:-root}
        links:
            - "pgsql:pgsql"
            
    basewebfrontend:
        container_name: basewebfrontend
        image: basewebfrontend:latest
        expose:
        - "80"
        
    redis:
        container_name: redis
        image: "redis:alpine"

    pgsql:
        container_name: pgsql
        image: postgres:9.5
        environment:
          POSTGRES_PASSWORD: ${PG_PASSWORD:-root}
        restart: on-failure
        volumes:
          - baseweb_data:/var/lib/postgresql/data

    mongodb:
        container_name: mongodb
        image: mongo:latest
        ports:
          - 27017:27017
        volumes:
          - baseweb_data:/var/lib/mongodb/data