# POSTGRES_DB: baseweb_dms config database name if in local
SERVICE_HOST: localhost
SERVICE_PORT: 8080
SQL_DB_HOST: localhost
SQL_DB_PORT: 5432
SQL_DB_USER: postgres
SQL_DB_PASS: 123456
POSTGRES_DB: baseweb2

server:
  servlet:
    context-path: '/api'

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${SQL_DB_HOST}:${SQL_DB_PORT}/${POSTGRES_DB}
    username: ${SQL_DB_USER}
    password: ${SQL_DB_PASS}

logging:
  file:
    path: logs
    name: baseweb.log
  level:
    root: INFO
    com:
      hust :
        baseweb : DEBUG
    org:
      springframework: INFO
  config: classpath:logback-dev.xml