# POSTGRES_DB: baseweb_dms config database name if in local
SERVICE_HOST: localhost
SERVICE_PORT: 8080
SQL_DB_HOST: ec2-54-234-44-238.compute-1.amazonaws.com
SQL_DB_PORT: 5432
POSTGRES_DB: d646r1abvh40hu
JDBC_DATABASE_USERNAME: jlxjammvroiomz
JDBC_DATABASE_PASSWORD: be8fd8650614977d00dacb36584f42be36ed2a260686aa66ca200eb0d0a7dbe2
JDBC_DATABASE_URL: jdbc:postgresql://ec2-54-234-44-238.compute-1.amazonaws.com:5432/d646r1abvh40hu

server:
  servlet:
    context-path: '/api'

spring:
  data:
    rest:
      detection-strategy: annotated
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
  redis:
    host: localhost
    port: 6379
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}

logging:
  file:
    path: logs
    name: baseweb.log
  level:
    root: INFO
    com:
      hust :
        baseweb : DEBUG
    org:
#      hibernate:
#        SQL: DEBUG
#        type: TRACE
      springframework: INFO
  config: classpath:logback-dev.xml
